version: '3.8'

services:
  astro:
    build:
      context: ./astro-app
      dockerfile: Dockerfile
    restart: always
    environment:
      GHOST_URL: ${GHOST_URL}
      GHOST_CONTENT_API_KEY: ${GHOST_CONTENT_API_KEY}
